In [1]:
import torch
import numpy as np

In [20]:
from tkinter import N


np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)


tensor2numpy = torch_data.numpy()




numpy_data
 [[0 1 2]
 [3 4 5]] 
torch_data
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [29]:
# abs
data = [-1,-2,1,2]
# transfer to float 32bit
tensor = torch.FloatTensor(data) 


print(
    '\nmean',
    '\nnumpy'  , np.mean(data),
    '\ntensor' ,torch.mean(tensor)
)


mean 
numpy 0.0 
tensor tensor(0.)


In [31]:
data = [[1,2],[3,4]]
# transfer to float 32bit
tensor = torch.FloatTensor(data)

print(
    '\nnumpy' , np.matmul(data,data),
    '\ntorch' , torch.mm(tensor,tensor)
)




numpy [[ 7 10]
 [15 22]] 
torch tensor([[ 7., 10.],
        [15., 22.]])


In [52]:
# Variable 
import torch
from torch.autograd import Variable

tensor = torch.FloatTensor([[1,2]
                           ,[3,4]])

variable = Variable(tensor , requires_grad=True )

t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)


# 將結果反向傳遞
v_out.backward()
# Variable 的梯度
# 1/4*2*Variable = > 1/2*Variable
print(variable.grad)



tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [49]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)